### ISSUE TITLE
run_aices.sh

### ISSUE THREAD

**Issue by AlongLove** [tinsir888/ai-computing-system-cambricon#1]
在yolov3-bcl下运行./run_aicse.sh没有输出的结果，你遇到过这种情况么

**Comment by tinsir888** [comment]
检查一下 pbtxt 文件的修改？

**Comment by AlongLove** [comment]
> 检查一下 pbtxt 文件的修改？

可以了，兄弟。我改的pbtxt的数值有些问题，谢啦

**Comment by ssss2233** [comment]
兄弟，可以上传一下yolov3的过程中的代码吗，tensorflow集成不太会，非常感谢

**Comment by tinsir888** [comment]
> 

抱歉哈，我做完了就删了，没有保存。

另：ddl 不是早过了吗？

**Comment by ssss2233** [comment]
谢谢兄弟，已经按照实验手册解决了（我是自学
